---

- name: Install MySQL server
  apt: name={{ item }} update_cache=yes force=yes state=installed
  with_items:
    - libmysqlclient-dev
    - mysql-server
    - python-mysqldb

- name: Create MySQL database if it doesn't exist
  mysql_db: name={{ db_name }}
            login_user={{ db_user}}
            login_password={{ db_pass }}
            collation=utf8_general_ci
            encoding=utf8
            state=present

- name: Create .my.cnf file with MySQL credentials
  template: src=my.cnf.j2
            dest={{ home_path }}/.my.cnf
            owner={{ user_name }}
            mode=0600
  sudo: no