---

- name: Install nginx
  apt: name={{ item }} update_cache=yes force=yes state=installed
  with_items:
    - nginx

- name: Create the Nginx configuration file for SSL
  template: src=site_ssl.conf.j2
            dest=/etc/nginx/sites-available/{{ project_name }}
            backup=yes
  when: use_ssl

- name: Create the Nginx configuration file (non-SSL)
  template: src=site.conf.j2
            dest=/etc/nginx/sites-available/{{ project_name }}
            backup=yes
  when: not use_ssl

- name: Ensure that the default site is removed
  command: rm /etc/nginx/sites-enabled/default
           removes=/etc/nginx/sites-enabled/default

- name: Ensure that the application site is enabled
  command: ln -s /etc/nginx/sites-available/{{ project_name }}
           /etc/nginx/sites-enabled/{{ project_name }}
           creates=/etc/nginx/sites-enabled/{{ project_name }}
  notify: reload nginx

- name: Ensure Nginx service is started, enable service on restart
  service: name=nginx state=restarted enabled=yes
  when: enabled

# needs to notify handler to come after the restart handlers
- name: Stop nginx for local dev, disable on restart
  service: name=nginx state=stopped enabled=no
  notify: stop nginx
  when: not enabled