---

- name: Configuration for local development on Vagrant VM
  hosts: all
  sudo: yes

  roles:
    - common
    - python
    - flask
    - { role: gunicorn, autostart: false, enabled: false }
    - { role: nginx, use_ssl: false, enabled: false }

  tasks:
    - name: Allow venv/bin/python to bind port 80
      command: setcap cap_net_bind_service=ep {{ home_path }}/venv/bin/python
