---

- name: Configuration for AWS Production
  hosts: all
  become: yes
  vars:
    user_name: "ubuntu"

  roles:
    - common
    - ntp
    - python
    - { role: gunicorn, autostart: true, enabled: true }
    - { role: nginx, use_ssl: false, enabled: true }
