---

- name: Configuration for staging/testing server
  hosts: localhost
  sudo: yes
  # remote_user: ubuntu

  vars_files:
    - project_vars.yml

  # similar to production, but no SSL, loads fixtures, and adds headless browser testing
  roles:
    - common
    - ntp
    - python
    - mysql
    - { role: django, settings_local: true, migrate: true, load_fixtures: true, collectstatic: true }
    - { role: gunicorn, autostart: true, enabled: true }
    - { role: nginx, use_ssl: false, enabled: true }
    - { role: browser, autostart: false }